# Generated by Django 4.0.5 on 2022-07-27 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCareRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneyowed', models.DecimalField(decimal_places=2, max_digits=7)),
                ('timeworked', models.TimeField()),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercarerel_careg', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercarerel_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
